-- 0004_fde_db_triage_content.sql
--
-- Populate the fde-db-triage scenario row (originally seeded as a placeholder
-- by 0003_fde_scenarios.sql) with the canonical scenario content from
-- docs/scenarios/crucible_scenario_fde-db-triage.md.
--
-- The canonical source-of-truth lives at fixtures/fde-db-triage/scenario.json;
-- this migration was generated from that file and is paired with
-- apps/server/scripts/encode-fde-db-triage.ts for environments without the
-- Supabase CLI. Either path produces the same row state.
--
-- Idempotent: re-running this migration overwrites the same row with the same
-- values.

UPDATE scenarios SET
  difficulty       = 'mid',
  dataset_ref      = 'fixtures/fde-db-triage',
  brief            = 'You''re the forward-deployed engineer assigned to Meridian, a B2B SaaS company. Their finance team has flagged that the monthly revenue dashboard looks materially too high for recent months, and leadership wants answers before a board meeting. You have read access to a copy of Meridian''s production database and an internal channel with your teammate. Figure out what''s going on, fix it, and give finance something they can trust. Your client (Dana, VP Finance) is in the client channel.',
  client_persona   = '{"name":"Dana","role":"VP Finance","voice":"non-technical, anxious, time-pressured","goal":"A trustworthy corrected revenue number plus a plain-English explanation she can take to the board.","knows":["The dashboard ''looks wrong, way too high.''","Numbers started looking off around April.","The board meeting is soon."],"never_reveals":["The technical root cause.","Anything about the database schema or SQL.","Any opinion about webhooks, retries, duplicates, refunds, or timezones."],"beats":[{"id":"open","trigger":"session_start","behavior":"Opens with the vague, urgent ask from the brief. Does not volunteer specifics."},{"id":"specifics_on_ask","trigger":"candidate_asks_clarifying_question","behavior":"Reveals: it''s the monthly recognized revenue tile; finance expected roughly $1.1M–$1.3M/mo; the dashboard shows ~$1.5M+; it started looking off around April."},{"id":"relief_on_update","trigger":"candidate_gives_status_update","behavior":"Expresses relief and adds slight extra pressure: ''Can you have it by end of session?''"},{"id":"curveball_1_relay","trigger":"curveball.requirement_change","behavior":"Relays leadership''s new ask: corrected figures for the last 3 months plus a one-paragraph board explanation, by end of session."},{"id":"skeptical_acceptance","trigger":"candidate_delivers_final","behavior":"Asks one skeptical follow-up — ''Are you sure this is the real number?'' — before accepting."}],"guardrails":["Never volunteers or confirms the technical cause.","If asked leading SQL-ish questions, redirects to business context.","Stays in character; does not coach the candidate."]}'::jsonb,
  team_persona     = '{"name":"Sam","role":"senior engineer / teammate","voice":"helpful but busy, slightly overconfident","goal":"Be helpful while mid-task; nudge the candidate without doing the work for them.","beats":[{"id":"misleading_hint","trigger":"early_session","behavior":"Proactively messages: ''the revenue thing? pretty sure it''s refunds not being subtracted, just filter those out.'' (Refunds are a red herring.)"},{"id":"concede_with_evidence","trigger":"candidate_pushes_back_with_evidence","behavior":"Concedes and offers a real clue: ''huh. payments come in via Stripe webhooks — worth checking for dupes if a retry misfired.'' Only fires if the candidate brings specific numbers showing refunds do not close the gap."},{"id":"scope_boundary","trigger":"candidate_asks_for_prod_access","behavior":"Declines: ''can''t pull prod creds, but the read replica you have should be enough.''"}],"guardrails":["Gives the misleading hint exactly once.","Never hands over the answer.","The real clue only unlocks if the candidate brings evidence (rewards verification over trust)."]}'::jsonb,
  constraints      = '{"time_minutes":90,"tokens":200000,"compute_minutes":60,"money_usd":25,"memory_mb":2048}'::jsonb,
  curveballs       = '[{"id":"requirement_change","trigger":{"kind":"time_or_event","time_offset_minutes":25,"event":"candidate_first_substantive_client_update"},"payload":{"channel":"client","speaker":"Dana","message":"Quick update from leadership — they now want the corrected figures for the last 3 months and a one-paragraph board explanation, by end of session."},"tests":["adaptability","reprioritization","outcome_communication"]},{"id":"misleading_teammate_hint","trigger":{"kind":"time_or_event","time_offset_minutes":3,"event":"session_start"},"payload":{"channel":"team","speaker":"Sam","message":"the revenue thing? pretty sure it''s refunds not being subtracted, just filter those out."},"tests":["verification_over_trust","teamwork"]}]'::jsonb,
  deliverable_spec = '{"components":[{"key":"corrected_monthly_revenue","label":"Corrected monthly revenue (last 3 months)","what":"A query or script that runs against the database and reproduces the corrected monthly revenue figures for March, April, and May 2026.","accept_criteria":["Query executes successfully against the seeded database.","Output is the corrected (dedup + status-filtered) revenue.","Numbers land within ±2% of the fixture''s ground-truth corrected figures."]},{"key":"root_cause_finding","label":"Root-cause finding","what":"A clear statement of what was wrong and why — duplicate payment rows from webhook retries, not the refund hypothesis the teammate proposed.","accept_criteria":["Identifies duplicate succeeded payments (same external_payment_id) as the cause.","Explicitly rejects the refund hypothesis with evidence.","Quantifies the duplicate rate and the resulting overstatement."]},{"key":"client_facing_summary","label":"Board-ready client-facing summary","what":"A one-paragraph explanation Dana can take to the board: the corrected number, plain-English cause, and that this is a recording bug (revenue was never actually that high). Recommends the upstream fix.","accept_criteria":["Written in plain language a non-technical board member can follow.","States the corrected figure clearly.","Makes clear that real revenue did not change — only the dashboard was wrong.","Recommends fixing the upstream webhook idempotency issue."]},{"key":"decisions_and_tradeoffs","label":"Key decisions and trade-offs","what":"A short engineering note: how refunds were handled, how the timezone question was resolved, the chosen dedup strategy, and what should be fixed upstream.","accept_criteria":["Addresses refund handling.","Addresses the UTC timestamp question.","Names the dedup approach (e.g., DISTINCT ON external_payment_id, or GROUP BY keeping MIN(id)).","Recommends an upstream change (idempotency key, retry-safe ingest)."]}]}'::jsonb,
  rubric           = '{"problem_framing":{"weight":0.15,"description":"Asks what ''wrong''/expected/when before digging; forms hypotheses before querying.","signals":["Client questions asked before first query.","Time-to-first-question vs time-to-first-query.","Hypotheses stated explicitly before testing them."]},"data_fluency":{"weight":0.2,"description":"Explores schema, finds the duplicates, quantifies the gap; does not accept the refund hint blindly.","signals":["Progression of db.query calls from exploration to targeted aggregation.","Dedup query present in the final solution.","Refund hypothesis explicitly tested and rejected with numbers."]},"design_under_constraints":{"weight":0.1,"description":"Uses targeted queries over full scans; manages compute and token budget; reprioritizes after the requirement change.","signals":["Constraint-spend trajectory (compute / tokens) stays below the displayed budgets.","Query selectivity (predicates on indexed columns, narrow projections).","Reprioritization observable after curveball 1."]},"execution":{"weight":0.2,"description":"Produces corrected figures that actually run and match ground truth.","signals":["Deliverable correctness vs ground truth within ±2%.","Working dedup query or script committed to the workspace.","All four deliverable components present."]},"ai_orchestration":{"weight":0.1,"description":"Uses the AI assistant to accelerate work but verifies its output against the data.","signals":["ai.assistant usage events followed by verification queries.","Does not paste assistant output as final without checking.","Recovers gracefully if the token budget runs low."]},"teamwork":{"weight":0.1,"description":"Engages the teammate, verifies the misleading hint rather than acting on it, escalates appropriately.","signals":["Exchange in the team channel before acting on the refund hint.","Refund hypothesis tested against the data, not just trusted.","Asks Sam follow-ups with specific evidence to unlock the real clue."]},"customer_engagement":{"weight":0.05,"description":"Sets expectations, updates the anxious client, absorbs the requirement change calmly.","signals":["Cadence and quality of client-channel updates.","Calm, non-defensive response to curveball 1.","Translates technical findings into client-appropriate language."]},"outcome_communication":{"weight":0.1,"description":"Board-ready paragraph is clear, accurate, non-technical, with the correct number and plain cause.","signals":["Final paragraph reads as board-appropriate prose.","Corrected number is stated clearly and matches the candidate''s own query.","Cause is described in plain English without jargon."]}}'::jsonb,
  success_criteria = '{"must":["Identifies duplicate payments as the root cause (not refunds).","Corrected last-3-month figures land within ±2% of the fixture''s true corrected numbers.","Delivers all four deliverable components."],"bonus":["Recommends the upstream idempotency fix, not just a one-off dedupe in the query."],"tolerance":{"revenue_pct":0.02}}'::jsonb
WHERE slug = 'fde-db-triage';
